name: Lint and Build

on:
  push:
    branches-ignore:
      - main
  pull_request:
  fork:

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check prettier
        run: npm run format:check

      - name: Check lint
        run: npm run lint:check

      - name: Build
        run: npm run build
