name: Publish npm packages

on:
  push:
    branches:
      - main

jobs:
  publish_npm:
    name: Publish packages to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check if packages exist
        id: check-packages
        run: |
          echo "::set-output name=initial_publish::false"
          if ! npm view ts-fetcher; then
            echo "::set-output name=initial_publish::true"
          fi

      - name: Publish packages
        if: steps.check-packages.outputs.initial_publish == 'true'
        run: pnpm publish -r --no-git-checks --access public

      - name: Publish with changeset
        if: steps.check-packages.outputs.initial_publish == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm changeset publish
