name: Publish packages to npm

on:
  push:
    branches: [main]

jobs:
  init:
    name: init environment
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
  build:
    name: init environment
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Build
        run: pnpm run build

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: pnpm run build

      - name: Publish changed packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run publish --token $NPM_TOKEN
